# Generated by Django 5.0.2 on 2025-05-20 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0003_alumnos_maestros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('lugar', models.CharField(max_length=255)),
                ('publico_objetivo', models.JSONField()),
                ('programa_educativo', models.CharField(blank=True, max_length=255, null=True)),
                ('responsable', models.CharField(max_length=255)),
                ('descripcion', models.TextField(max_length=300)),
                ('cupo_maximo', models.PositiveIntegerField()),
            ],
        ),
    ]
