# Generated by Django 5.0.2 on 2025-05-20 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0004_evento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tipo_evento', models.CharField(max_length=100)),
                ('fecha_realizacion', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('lugar', models.CharField(max_length=255)),
                ('publico_json', models.JSONField()),
                ('programa_educativo', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField()),
                ('cupo_maximo', models.PositiveIntegerField()),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
