# Generated by Django 5.0.2 on 2025-05-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0005_eventos_delete_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='cupo_maximo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='publico_json',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='responsable',
            field=models.IntegerField(),
        ),
    ]
