# Generated by Django 5.0.2 on 2025-05-21 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0006_alter_eventos_cupo_maximo_alter_eventos_publico_json_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='responsable',
            new_name='ponente',
        ),
    ]
