# Generated by Django 5.0.2 on 2025-05-21 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0008_rename_ponente_eventos_responsable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='responsable',
            new_name='ponente',
        ),
    ]
