# Generated by Django 5.0.2 on 2025-05-21 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0009_rename_responsable_eventos_ponente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='ponente',
            new_name='responsable',
        ),
    ]
